server:
  port: 8081
  servlet:
    context-path: /hospital

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.113.142:3306/HospitalReversation?characterEncoding=utf-8
    username: root
    password: GMF!seeyoujune9th
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
